{'110A': Service(protocol='L2CAP', name='Advanced Audio', service_id=None,
                 profiles=[('110D', 258)], service_classes=['110A'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=25,
                 description=None),
 '110F': Service(protocol='L2CAP', name=None, service_id=None,
                 profiles=[('110E', 260)], service_classes=['110E', '110F'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=23,
                 description=None),
 'FAFBDD20-83F0-4389-ADDF-917AC9DAE5B2': Service(protocol='RFCOMM', name='Flow',
                                                 service_id=None, profiles=[],
                                                 service_classes=[
                                                     'FAFBDD20-83F0-4389-ADDF-917AC9DAE5B2'],
                                                 host='C0:EE:FB:D5:FC:A2',
                                                 provider=None, port=4,
                                                 description=None),
 '110E': Service(protocol='L2CAP', name=None, service_id=None,
                 profiles=[('110E', 260)], service_classes=['110E', '110F'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=23,
                 description=None),
 '1105': Service(protocol='RFCOMM', name='OBEX Object Push', service_id=None,
                 profiles=[('1105', 258)], service_classes=['1105'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=8,
                 description=None),
 '110C': Service(protocol='L2CAP', name='AV Remote Control Target',
                 service_id=None, profiles=[('110E', 260)],
                 service_classes=['110C'], host='C0:EE:FB:D5:FC:A2',
                 provider=None, port=23, description=None),
 '1801': Service(protocol='L2CAP', name=None, service_id=None, profiles=[],
                 service_classes=['1801'], host='C0:EE:FB:D5:FC:A2',
                 provider=None, port=31, description=None),
 '111F': Service(protocol='RFCOMM', name='Handsfree Gateway', service_id=None,
                 profiles=[('111E', 262)], service_classes=['111F', '1203'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=3,
                 description=None),
 '1204': Service(protocol='RFCOMM', name='SIM Access', service_id=None,
                 profiles=[('112D', 258)], service_classes=['112D', '1204'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=7,
                 description=None),
 '1132': Service(protocol='RFCOMM', name='SMS/MMS', service_id=None,
                 profiles=[('1134', 258)], service_classes=['1132'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=6,
                 description=None),
 '1800': Service(protocol='L2CAP', name=None, service_id=None, profiles=[],
                 service_classes=['1800'], host='C0:EE:FB:D5:FC:A2',
                 provider=None, port=31, description=None),
 '1203': Service(protocol='RFCOMM', name='Handsfree Gateway', service_id=None,
                 profiles=[('111E', 262)], service_classes=['111F', '1203'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=3,
                 description=None),
 '1112': Service(protocol='RFCOMM', name='Headset Gateway', service_id=None,
                 profiles=[('1108', 258)], service_classes=['1112', '1203'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=2,
                 description=None),
 '1115': Service(protocol='L2CAP', name='Android Network User', service_id=None,
                 profiles=[('1115', 256)], service_classes=['1115'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=15,
                 description='PANU'),
 '1116': Service(protocol='L2CAP', name='Android Network Access Point',
                 service_id=None, profiles=[('1116', 256)],
                 service_classes=['1116'], host='C0:EE:FB:D5:FC:A2',
                 provider=None, port=15, description='NAP'),
 '112D': Service(protocol='RFCOMM', name='SIM Access', service_id=None,
                 profiles=[('112D', 258)], service_classes=['112D', '1204'],
                 host='C0:EE:FB:D5:FC:A2', provider=None, port=7,
                 description=None),
 '112F': Service(protocol='RFCOMM', name='OBEX Phonebook Access Server',
                 service_id=None, profiles=[('1130', 258)],
                 service_classes=['112F'], host='C0:EE:FB:D5:FC:A2',
                 provider=None, port=5, description=None)}
